[project]
name = "copypastel"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "requests[socks]>=2.32.3",
]

[tool.ruff]
line-length = 100
lint.select = ["ALL"]
lint.ignore = ["D", "S311", "T201"]

[tool.pyright]
typeCheckingMode = "strict"
